---
# vars file for docker_bookstack

app_name:  drawio

network_base_container: 
      - '{{ "mail-relay" if  mailrelay_enabled else _ | default(omit) }}'
      - traefik

app_docker_labels:
      traefik.docker.network:                        'frontend'
      traefik.enable:                                'true'
      traefik.frontend.rule:                         'Host:{{ app_server_fqdn }}'
      traefik.port:                                  '8080'
      traefik.protocol:                              'http'
      traefik.frontend.headers.referrerPolicy:       'no-referrer'
      traefik.frontend.headers.SSLRedirect:          'true'
      traefik.frontend.headers.STSSeconds:           '315360000'
      traefik.frontend.headers.browserXSSFilter:     'true'
      traefik.frontend.headers.contentTypeNosniff:   'true'
      traefik.frontend.headers.forceSTSHeader:       'true'
      traefik.frontend.headers.STSIncludeSubdomains: 'true'
      traefik.frontend.headers.STSPreload:           'true'
      traefik.frontend.headers.frameDeny:            'true'
      com.centurylinklabs.watchtower.enable:         '{{ app_watchtower }}'
