---
# tasks file for docker_drawio
# start all needed drawio container

- name: '{{ app_name }} | include vars'
  include_vars: "{{ item }}"
  loop:
    - group_vars/drawio.yml

- name: '{{ app_name }} | drawio network'
  include_tasks: network.yml

- name: '{{ app_name }} | drawio container'
  include_tasks: drawio.yml
